---
name: "Sceptre Github CI Action"
description: "Run Sceptre with a GitHub Action"
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  sceptre_subcommand:
    description: "Sceptre subcommand to execute"
    required: true
  sceptre_version:
    description: "Version of Sceptre to install"
    required: false
    default: ""
  sceptre_directory:
    description: "Directory to execute Sceptre commands from"
    required: false
    default: ""
  sceptre_troposphere:
    description: "Specify if troposphere templates are used - 'true' or 'false'"
    required: false
    default: "false"
  sceptre_troposphere_version:
    description: "Version of troposphere to install"
    required: false
    default: "2.7.1"
  sceptre_plugins:
    description: "List of packages (and optionally, versions) to be passed to 'pip install'"
    required: false
    default: ""
  sceptre_requirements:
    description: "File path to a Pip requirements file (relative to repository root)"
    required: false
    default: ""
  sceptre_pipfile:
    description: "File path to a Pipenv Pipfile (relative to repository root)"
    required: false
    default: ""
runs:
    using: "docker"
    image: "./Dockerfile"
